// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // NOTE:
  // This config is used by Prisma CLI (migrate, studio, etc.). The datasource URL
  // is already defined in prisma/schema.prisma via env("DATABASE_URL").
  // The `adapter` field is not part of SchemaEngineConfigClassicDatasource and
  // breaks `next build` type-check in this repo.
});
